﻿version: '3.7'

services:
  api:
    image: api_image
    container_name: api_container
    ports:
      - "2023:80"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - api_network

  api_db:
    image: postgres:latest
    container_name: api_db
    environment:
      - POSTGRES_PASSWORD=asd12345
      - POSTGRES_User=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - api_volume:/var/lib/postgresql/data/
    networks:
      - api_network

networks:
    api_network:
        driver: bridge

volumes: 
    api_volume:  